Require espruinotools as Espruino
To avoid the error below:

ReferenceError: Espruino is not defined
    at parseJS (eval at <anonymous> (/home/romek/Bangle/BangleApps/bin/thumbnailer.js:43:1), <anonymous>:95:5)
    at eval (eval at <anonymous> (/home/romek/Bangle/BangleApps/bin/thumbnailer.js:43:1), <anonymous>:166:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)